### ISSUE TITLE
Query customer address 

### ISSUE THREAD

**Issue by aalbanese10** [CSCI-GA-2820-SP24-001/customers#25]
**As** eCommerce employee,
**I need** to sort the list of customers by address
**So that** I can search a specific customers by address

### Details and Assumptions
- Employee can select and filter what address fields of information they want to request
- An empty field will return an empty field

### Acceptance Criteria
 ```gherkin
When an employee requests for a list of customers with specified addresses,
the database will return a table with all the customers and corresponding information of each customer.

**Comment by maiko-chin** [comment]
Would the story point be on the capability to "sort" the customers? Or to "find" customers?

If it is to find, would it look more like "As an eCommerce employee, I want to search (or filter) for specific customers by address, so that I can [do something with the customers info, e.g. send targeted info to customers in a specific area]"

Probably not the best "so that" example.
This is the description of "I need" on Atlassian: _Here we’re describing their intent — not the features they use. What is it they’re actually trying to achieve? This statement should be implementation free — if you’re describing any part of the UI and not what the user goal is you're missing the point._

This comment also applies to other stories in this sprint.
